### ISSUE TITLE
Little Light/Dark mode bug in UI

### ISSUE THREAD

**Issue by noctera** [vocascan/vocascan-frontend#130]
We have a small bug in our UI leaving the `Vocascan` next to our logo black while in light mode. When turning it to dark mode everything works just fine.
Changing the color in the scss file itself won't fix it, as this color is used for the font too. Maybe you just have to introduce another color variable or have a look at the color variable used for the [NavButtons](https://github.com/vocascan/vocascan-frontend/tree/main/src/Components/Nav) as they are styled as intended.

Dark-mode:
![image](https://user-images.githubusercontent.com/54618409/192107964-133bec1e-0788-4220-a514-ed16e8e43fc6.png)

Light-mode:
![image](https://user-images.githubusercontent.com/54618409/192107982-c28da592-91c4-49c8-9f82-d628d6c04e48.png)

**Comment by IAmTamal** [comment]
You said `Changing the color in the scss file itself won't fix it` ,  but in the scss we have used `.top-nav .title p` 

- Since the Navbar's Logo, Title will not be changing ever can we keep it white ? 
- Currently it is set to ` color: $color-main-text;`, what if we set the color to `color:white`
- That way it won't change, because it doesnot have to change.

**Comment by noctera** [comment]
Yeah this would work with the current themes. But we want to have it flexible. In the future there might be Themes that require a black font instead of a white font. This can't be solved with a fixed white value, but instead with a variable

**Comment by aritroCoder** [comment]
Can you assign this to me, I want to work

**Comment by noctera** [comment]
> Can you assign this to me, I want to work

I haven't heard anything from @IAmTamal about solving this issue, so you can work on it

**Comment by aritroCoder** [comment]
Just a small question, how do I get the docker database URL to set up `vocascan.config.js`?

**Comment by noctera** [comment]
Your can either expose the port with
`
ports:
  - 5432:5432
`
And access the database via `127.0.0.1` and port 5432

Or use the name of the service, as shown here:
https://github.com/vocascan/vocascan-server/tree/main/docker%2Fdefault

(Maybe this config file might be a little too old, and one or two options might be missing. But in this case you will get noticed on the start if anything has changed. But i think this minimum configuration is still working)

**Comment by aritroCoder** [comment]
When I try to create a session using `docker-compose exec vocascan ash` I get the response:
```
Error response from daemon: Container 91f73df2fd701359d02dae649d11ab1c3c925c000ac321c8a709744514441f67 is restarting, wait until the container is running
```
I don't know much about docker so if you can help me fix it then it will be very helpful

**Comment by luwol03** [comment]
@aritroCoder This means your container crashed and keeps restarting. So you have to figure out why. Please open a discussion for that and provide more details (logs (`docker-compose logs -f`), your `docker-compose.yml` file, commands you executed, ...)

**Comment by noctera** [comment]
@aritroCoder If you can't get a server up and running, you can use our internal development server. But keep in mind that you mustn't store personal data on this account, as they are just for development and might be deleted without a warning. For a personal usage, take our cloud.
The dev server is reachable under this domain: https://test-server.vocascan.com
having the following accounts:

```
1. Username: test1; Password: test1;
2. Username: test2; Password: test2;
...
9. Username: test9; Password: test9;
```

**Comment by aritroCoder** [comment]
thanks, I had set up the server, now if I am changing some files I am not seeing it to update, I had tried hard reloading and clearing cache but its still the same

**Comment by luwol03** [comment]
How have you set up your server? Which files have you changed?

**Comment by aritroCoder** [comment]
docker-compose.ymll file: 
```
version: '3.8'
services:
  vocascan:
    image: vocascan/server:latest
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      VOCASCAN_CONFIG: '/vocascan.config.js'
    ports:
      - '6000:80'
    volumes:
      - './vocascan.config.js:/etc/vocascan/vocascan.config.js:ro'
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'vocascan'
      POSTGRES_PASSWORD: 'vocascan'
      POSTGRES_DB: 'vocascan'
    volumes:
      - './database:/var/lib/postgresql/data'
  frontend:
    image: vocascan/frontend:latest
    restart: always
    tty: true
    environment:
      VOCASCAN_BASE_URL: "https://test-server.vocascan.com"
    ports:
      - "3000:80"
```
vocascan.config,js
```
/**
 * For more help with the file see https://docs.vocascan.com/#/vocascan-server/configuration
 * This config file lists all available options
 */

module.exports = {
  debug: false,

  server: {
    port: 8000,
    jwt_secret: '',
    salt_rounds: 10,
  },

  database: {
    dialect: 'postgres',
    host: 'db',
    port: '5432',
    username: 'vocascan',
    password: 'vocascan',
    database: 'vocascan',
  },

  log: {
    console: {
      level: 'info',
      colorize: true,
      enable_sql_log: true,
      enable_router_log: true,
      stderr_levels: ['error'],
    },
  },
};
```
file trying to change: `src/components/Nav/TopNav.jsx
